#!/bin/bash
DIRNAME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
NODE_VERSION=$(cat $DIRNAME/.nvmrc)

setupCorepack(){
  CORE_PATH=$DIRNAME/tools/node-$NODE_VERSION

  if [[ ! -d $CORE_PATH ]]; then
    mkdir -p $CORE_PATH
    corepack enable --install-directory="$CORE_PATH"
  fi
}

setupCorepack
NODE_PATH="$(which node)"

if [ "$1" != "--verify" ]; then
  "$NODE_PATH" "$@"
fi
